data:
  root_path: "/home/kamil/Datasets/chains"
  solo_path: "/home/kamil/Datasets/chains/solo"
  whsp_path: "/home/kamil/Datasets/chains/whsp"
  split_ratio: 0.05

model:
  name: "redimnet-b6"

training:
  batch_size: 32
  epochs: 300
  optimizer: "adamw"
  lr: 1e-4

  