data:
  solo_path: "/lustre/pd01/hpc-maggol5711-1768234235/datasets/chains/solo/"
  whsp_path: "/lustre/pd01/hpc-maggol5711-1768234235/datasets/chains/whsp/"
  split_ratio: 0.7
model:
  name: "redimnet-b6"
  head: "cosine"

baseline:
  model_names:
    - "redimnet-b6"
    - "redimnet-b4"
    - "redimnet-b2"
  results_filename: "baselines.json"

wandb:
  project_name: "whispered_sv"

training:
  batch_size: 128
  epochs: 100
  optimizer: "adamw"
  lr: 1e-4
  lr_ft: 1e-5
  weight_decay: 1e-4
  seed: 43
  gammas:
    - 1e-4
    - 0.5
  use_amp: true
  eval_modes:
    - "neutral-neutral"
    - "neutral-whisper"
    - "whisper-whisper"
    - "all"
  unfreezing_schedule:
    30:
      - "backbone.stage0"
    25:
      - "backbone.stage1"
    20:
      - "backbone.stage2"
    15:
      - "backbone.stage3"
    10:
      - "backbone.stage4"
    5:
      - "backbone.stage5"
    1:
      - "backbone.fin_wght1d.w"
      - "pool.linear1.weight"
      - "pool.linear1.bias"
      - "pool.linear2.weight"
      - "pool.linear2.bias"
      - "bn.weight"
      - "bn.bias"
      - "linear.weight"
      - "linear.bias"
  device: "cuda"
  speaker_head_name: "AAMSoftmax"
  speaker_head_scale: 30.0
  speaker_head_margin: 0.2


linear_probe:
  mode: "speaker-whisper-whisper"
  n_epochs: 20
  

  