data:
  root_path: "/home/kamil/Datasets/chains"
  solo_path: "/lustre/pd01/hpc-maggol5711-1768234235/datasets/chains/solo/"
  whsp_path: "/lustre/pd01/hpc-maggol5711-1768234235/datasets/chains/solo/"
  split_ratio: 0.6

model:
  name: "redimnet-b6"

training:
  batch_size: 2
  epochs: 300
  optimizer: "adamw"
  lr: 1e-4

  